- src/main/kotlin/net/revanced/patcher/Patcher.kt
- src/main/kotlin/net/revanced/patcher/cache/Cache.kt
- src/main/kotlin/net/revanced/patcher/cache/PatchData.kt
- src/main/kotlin/net/revanced/patcher/resolver/MethodResolver.kt
- src/main/kotlin/net/revanced/patcher/util/Jar2ASM.kt
- src/test/kotlin/net/revanced/patcher/PatcherTest.kt
This PR increases the speed of caching the methods and classes. Instead of moving all the methods and classes from one to another map or list we simply instantiate the Cache with them. Additionally the example test `testPatcher` has been improved.
> Improve example test `testPatcher` and increase caching speed

- src/main/kotlin/net/revanced/patcher/resolver/MethodResolver.kt
- src/main/kotlin/net/revanced/patcher/signature/Signature.kt
- src/test/kotlin/net/revanced/patcher/PatcherTest.kt
RE: #9 
This commit will allow "partial" signatures. Example usage:
```kt
val showVideoAdsMethodData = cache.methods["show-video-ads"].findParentMethod(
Signature(
"show-video-ads-method",
null,
null,
arrayOf(Type.BOOLEAN_TYPE),
null
)
) ?: return PatchResultError("Could not find parent method to 'show-video-ads'")
```
This example will try to use the cached method `show-video-ads` to find the actual method `show-video-ads-method`. To find this method in our example, it is only required to match for the parameters, since in our example, no other method in the same class has this parameter.
> fix: nullable signature members

- src/main/kotlin/net/revanced/patcher/Patcher.kt
- src/main/kotlin/net/revanced/patcher/cache/Cache.kt
- src/main/kotlin/net/revanced/patcher/cache/PatchData.kt
- src/main/kotlin/net/revanced/patcher/util/Io.kt
- src/main/kotlin/net/revanced/patcher/writer/ASMWriter.kt
- src/test/kotlin/net/revanced/patcher/PatcherTest.kt
- src/test/kotlin/net/revanced/patcher/ReaderTest.kt
- src/test/kotlin/net/revanced/patcher/util/TestUtil.kt
Io will now be instantiated with both, input as well as an output stream alongside a mutable class list:
https://github.com/ReVancedTeam/revanced-patcher/blob/0f3db838a05fb376fe974b4a1bb3292888f8c5a0/src/main/kotlin/net/revanced/patcher/util/Io.kt#L13-L17
The streams are used until we call `saveAsJar`. The original streams will be closed:
https://github.com/ReVancedTeam/revanced-patcher/blob/0f3db838a05fb376fe974b4a1bb3292888f8c5a0/src/main/kotlin/net/revanced/patcher/util/Io.kt#L86-L90
When writing, the input stream will be proxied through a  `BufferedInputStream` a second time, all classes will be merged with all non-class file zip entries and written into the output stream:
https://github.com/ReVancedTeam/revanced-patcher/blob/0f3db838a05fb376fe974b4a1bb3292888f8c5a0/src/main/kotlin/net …
> fix(Io): JAR loading and saving

- src/main/kotlin/app/revanced/patcher/resolver/MethodResolver.kt
- src/main/kotlin/app/revanced/patcher/signature/Signature.kt
- src/test/kotlin/app/revanced/patcher/PatcherTest.kt
Changes:
- Change `Array<Int>` references to `IntArray`
---------------------------------------------------
This is to ensure no unnecessary boxing/unboxing happens when running the patcher.
This will break current patches, but migration is really easy - change all `arrayOf()` occurrences for `opcode` to `intArrayOf()`. If this PR gets merged, I'd be glad to migrate the [current patches](https://github.com/ReVancedTeam/revanced-patches) myself.
> refactor: Optimize Signature class

- src/main/kotlin/app/revanced/patcher/signature/MethodSignature.kt
- src/main/kotlin/app/revanced/patcher/signature/resolver/SignatureResolver.kt
- src/test/kotlin/app/revanced/patcher/usage/ExamplePatch.kt
This PR adds the capability to search for strings in a method by defining a list of strings in a `MethodSignature`. Currently inefficient.
> feat: string signature

- src/main/kotlin/app/revanced/patcher/smali/InlineSmaliCompiler.kt
Makes it easier to reference the `this` register in virtual methods or parameters in general.
E.g.
```kt
// p0 (same as v2) refers to the first parameter of some static method
"return p0".toInstruction("BZI", 5)
```
Passing the method's parameter signature and register count is necessary so smali can calculate the corresponding `v` register number.
> Add `p` naming scheme to smali compiler

- src/main/kotlin/app/revanced/patcher/Patcher.kt
- src/main/kotlin/app/revanced/patcher/patch/annotations/PatchAnnotation.kt
- src/test/kotlin/app/revanced/patcher/usage/bytecode/ExampleBytecodePatch.kt
`DependencyType.SOFT` has now been removed after it was deprecated. There is no direct replacement for this.
Please look into Patch Options instead, which supersedes this:
https://github.com/revanced/revanced-patcher/blob/711b8a25a7c2842270b06e831ee7844a2c86d7c2/src/test/kotlin/app/revanced/patcher/usage/bytecode/ExampleBytecodePatch.kt#L167-L180
> refactor: remove DependencyType.SOFT

- src/main/kotlin/app/revanced/patcher/Patcher.kt
Resources should always be closed when they are not used any more.
This PR fixes the issue by closing `ExtFile`s created explicitly.
> fix: close ExtFiles

- src/main/kotlin/app/revanced/patcher/Patcher.kt
- src/main/kotlin/app/revanced/patcher/util/TypeUtil.kt
This PR makes classes public, if public missing methods or fields are to be merged into them. This is necessary because ART apparently requires the class to be public, regardless of the access of the methods and fields. The issue this PR fixes can be reproduced with the `block-embedded-ads` patch for Twitch. The integrations class contains public methods, and therefore the class is also public. Because these methods do not exist in Twitch, it was necessary to merge them, requiring the class to be public as well. Superclasses are considered in this PR recursively, as well.
> fix: publicize types when merging files if necessary

- build.gradle.kts
This PR updates the dependency `app.revanced:multidexlib2` to address revanced/multidexlib2/issues/2.
> build: update dependency `app.revanced:multidexlib2`

- .gitignore
- gradle/wrapper/gradle-wrapper.properties
And also ignore gradle.properties, we don't want to share the github token.
This change is necessary to compile the project with Java 19. Gradle 8 doesn't introduce any breaking changes to the workflow as far as I've tested
> Update Gradle wrapper to 8.0.1

- src/main/kotlin/app/revanced/patcher/fingerprint/method/impl/MethodFingerprint.kt
Passes the `ClassDef` into the `customFingerprint` method on `MethodFingerprint`.
Closes #164
> feat!: Expose ClassDef in MethodFingerprint

- src/main/kotlin/app/revanced/patcher/extensions/Extensions.kt
Implemented TODO
Provides stronger matching and gives a slight speed up (around 2-3 seconds improvement when patching YouTube on a laptop), but this also means some existing patches will need updating because the method signature parameters are not the correct order.
edit: all YouTube patches function correctly, also all 'universal' patches work ok as well.
> fix: compare method fingerprint parameter order

- src/main/kotlin/app/revanced/patcher/fingerprint/method/impl/MethodFingerprint.kt
fix for NPE if a fingerprint specifies access/return/parameters that do not match any methods in the target app.
> fix: null pointer exception if fingerprint specified a non existent signature

- src/main/kotlin/app/revanced/patcher/Patcher.kt
- src/main/kotlin/app/revanced/patcher/fingerprint/method/impl/MethodFingerprint.kt
Since the patcher stays in memory, patching in Manager multiple times (without restarting the app) always fails on the second patch.   The lookup maps to be cleared after patching finishes.
This fix should be pushed out now, and Manager needs another dependency update and release.
> fix: clear method lookup maps

- src/main/kotlin/app/revanced/patcher/Patcher.kt
- src/main/kotlin/app/revanced/patcher/fingerprint/method/impl/MethodFingerprint.kt
Right now, if we abort the patching process after merging integrations, we need to restart the app to start another patching process.
This PR aims to clear the maps from previous patching session so that new session can be started at any time.
> fix: clear `FingerprintResolutionLookupMaps` before patching

- revanced-patcher/src/main/kotlin/app/revanced/patcher/patch/Patch.kt
- revanced-patcher/src/main/kotlin/app/revanced/patcher/patch/PatchResult.kt
- revanced-patcher/src/main/kotlin/app/revanced/patcher/util/smali/InlineSmaliCompiler.kt
If the device uses a RTL language then patching fails with a syntax error:
```
Caused by: java.lang.IllegalStateException: Encountered 1 parser syntax errors and 0 lexer syntax errors!
at app.revanced.patcher.util.smali.InlineSmaliCompiler$Companion.compile(InlineSmaliCompiler.kt:49)
at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstructions(InlineSmaliCompiler.kt:72)
at app.revanced.patcher.util.smali.InlineSmaliCompilerKt.toInstruction(InlineSmaliCompiler.kt:84)
at app.revanced.patcher.extensions.InstructionExtensions.addInstruction(InstructionExtensions.kt:92)
at app.revanced.patches.shared.integrations.AbstractIntegrationsPatch$IntegrationsFingerprint.invoke(AbstractIntegrationsPatch.kt:43)
at app.revanced.patches.shared.integrations.AbstractIntegrationsPatch.execute(Abstr …
```
> fix: Fix SMALI compilation on devices with RTL language

- .editorconfig
- api/revanced-patcher.api
- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- src/main/kotlin/app/revanced/patcher/IntegrationsConsumer.kt
- src/main/kotlin/app/revanced/patcher/InternalApi.kt
- src/main/kotlin/app/revanced/patcher/PackageMetadata.kt
- src/main/kotlin/app/revanced/patcher/Patcher.kt
- src/main/kotlin/app/revanced/patcher/PatcherConfig.kt
- src/main/kotlin/app/revanced/patcher/PatcherContext.kt
- src/main/kotlin/app/revanced/patcher/PatcherOptions.kt
- src/main/kotlin/app/revanced/patcher/PatcherResult.kt
- src/main/kotlin/app/revanced/patcher/data/BytecodeContext.kt
- src/main/kotlin/app/revanced/patcher/data/ResourceContext.kt
- src/main/kotlin/app/revanced/patcher/patch/BytecodePatch.kt
- src/main/kotlin/app/revanced/patcher/patch/Patch.kt
- src/main/kotlin/app/revanced/patcher/patch/RawResourcePatch.kt
- src/main/kotlin/app/revanced/patcher/util/Document.kt
- src/main/kotlin/app/revanced/patcher/util/DomFileEditor.kt
- src/test/kotlin/app/revanced/patcher/patch/PatchInitializationTest.kt
- src/test/kotlin/app/revanced/patcher/patch/usage/ExampleResourcePatch.kt
This PR allows reading and writing arbitrary files in an APK file. Additionally, it allows deleting files from APK files. A `RawResourcePatch` class has been added, which has access to `ResourceContext` but ReVanced Patcher will not decode APK resources. A regular `ResourcePatch` can read and write arbitrary files from an APK file unless they are decoded to `PatcherConfig.apkFiles`. On an attempt to get a file from `PatcherConfig.apkFiles` if the second parameter is true, it will read and write the raw resource file from the original APK to `PatcherConfig.apkFiles` if it does not exist. With this commit, many APIs have been deprecated as well, such as `DomFileEditor` and instead, a `Document` has been added.
> feat: Read and write arbitrary files in APK files

- docs/2_patches_intro.md
The `resourcePatch` value was constructed from the `RawResourcePatch` which is a bit misleading. Also use the 1st letter uppercase convention from Kotlin.
> docs: tipo resource using rawResource

- src/main/kotlin/app/revanced/patcher/patch/BytecodePatchContext.kt
Fixes patching failure when using Manger and Android 12 or lower.
All other patcher code seems to compile just fine.
Changing the project Android SDK to 8.0 correctly detects the issue.  I'm not sure if Android 8.0 can be set in a gradle config file or somewhere else, as changing the project in Android Studio does not change any project files.
> fix: Make it work on Android 12 and lower by using existing APIs

- src/main/kotlin/app/revanced/patcher/Patcher.kt
- src/main/kotlin/app/revanced/patcher/patch/BytecodePatchContext.kt
- src/main/kotlin/app/revanced/patcher/patch/Patch.kt
- src/test/kotlin/app/revanced/patcher/PatcherTest.kt
This PR changes how extensions are merged. Before, all extensions were merged unconditionally regardless of whether a patch succeeded. This was done to reduce memory overhead since the lookup map for the merge could be removed after all extensions were merged. Now, an extension of a patch is merged right before the patch is executed. This requires the lookup map to be kept in memory as long as the patches are executing. This should not be much of a problem. The maps are cleared after all patches were executed
> fix: Merge extension only when patch executes

- api/revanced-patcher.api
- docs/1_patcher_intro.md
- docs/2_1_setup.md
- docs/2_2_1_fingerprinting.md
- docs/2_2_patch_anatomy.md
- docs/2_patches_intro.md
- docs/4_apis.md
- src/main/kotlin/app/revanced/patcher/Fingerprint.kt
- src/main/kotlin/app/revanced/patcher/Patcher.kt
- src/main/kotlin/app/revanced/patcher/PatcherConfig.kt
- src/main/kotlin/app/revanced/patcher/patch/BytecodePatchContext.kt
- src/main/kotlin/app/revanced/patcher/patch/Patch.kt
- src/main/kotlin/app/revanced/patcher/util/ClassMerger.kt
- src/test/kotlin/app/revanced/patcher/PatcherTest.kt
- src/test/kotlin/app/revanced/patcher/patch/PatchTest.kt
Should be merged after https://github.com/ReVanced/revanced-patcher/pull/315
Fingerprints can now be matched easily without adding them to a patch first. For reference, see the updated docs in the PR branch.
BREAKING CHANGE: Many APIs have been changed.
> feat: Improve Fingerprint API

- src/main/kotlin/app/revanced/patcher/patch/BytecodePatchContext.kt
`this::javaClass.name` returns a wrong name
```kt
println(this::javaClass.name)
// javaClass
println(this::class.java.name)
// app.revanced.patcher.patch.BytecodePatchContext
```
And the logger is configured to output logs whose loggerName starts with "app.revanced".
As a result, log messages in `BytecodePatchContext` was not printed on both CLI and Manager.
This PR fixes this problem.
> fix: Add back missing log by naming logger correctly

- api/revanced-patcher.api
- src/main/kotlin/app/revanced/patcher/util/Document.kt
As ToSteam (used by XMLTransformer) writes char by char, using a buffered writer improves significantly the performance of the writing.
See #339 for the tests and the discussion
> perf: Use a buffered writer to reduce IO overhead

- src/main/kotlin/app/revanced/patcher/util/Document.kt
The android implementation of the transformer encodes the emoji in a form called "surrogate", but aapt and apktool do not understand the surrogate form. Thus, detect surrogate and recompute the traditional code point value before writing it to file allowing aapt and apktool to rebuild the app successfully.
It should fix some cases (mainly for google app) of https://github.com/ReVanced/revanced-manager/issues/2142
> fix: Encode XML files as UTF-8 to fix compilation of resources
